package com.runloyal.booking.service;
import com.runloyal.booking.context.TenantContext; import com.runloyal.booking.domain.*; import com.runloyal.booking.repo.Repos; import com.runloyal.booking.web.Dto.*; import jakarta.transaction.Transactional; import org.springframework.stereotype.*; import java.time.*; import java.util.*;
@Service public class PlatformService { final TenantContext ctx; final Repos.Tenants tenants; final Repos.Services services; final Repos.Staffs staffs; final Repos.Assignments assignments; final Repos.Availabilities avails; final Repos.Bookings bookings; final AvailabilityEngine engine=new AvailabilityEngine(); public PlatformService(TenantContext c,Repos.Tenants t,Repos.Services s,Repos.Staffs st,Repos.Assignments a,Repos.Availabilities av,Repos.Bookings b){ctx=c;tenants=t;services=s;staffs=st;assignments=a;avails=av;bookings=b;}
 UUID tenant(){return ctx.tenantId();} void admin(){ctx.requireAdmin();} ZoneId zone(){return ZoneId.of(tenants.findById(tenant()).orElseThrow().timezone);} <T> T found(Optional<T> x){return x.orElseThrow(()->new NoSuchElementException("Resource not found"));}
 public List<ServiceOffering> services(){return services.findByTenantId(tenant());} @Transactional public ServiceOffering saveService(ServiceCommand c,UUID id){admin();ServiceOffering s=id==null?new ServiceOffering():found(services.findByIdAndTenantId(id,tenant())); if(id==null)s.tenantId=tenant(); s.name=c.name();s.description=c.description();s.category=c.category();s.durationMinutes=c.durationMinutes();s.price=c.price();s.status=c.status()==null?Model.Status.ACTIVE:c.status();return services.save(s);} @Transactional public void deleteService(UUID id){admin();services.delete(found(services.findByIdAndTenantId(id,tenant())));}
 public List<Staff> staffs(){return staffs.findByTenantId(tenant());} @Transactional public Staff saveStaff(StaffCommand c,UUID id){admin();Staff s=id==null?new Staff():found(staffs.findByIdAndTenantId(id,tenant()));if(id==null)s.tenantId=tenant();s.name=c.name();s.status=c.status()==null?Model.Status.ACTIVE:c.status();return staffs.save(s);}
 @Transactional public void assign(UUID service,UUID staff,boolean add){admin();found(services.findByIdAndTenantId(service,tenant()));found(staffs.findByIdAndTenantId(staff,tenant()));var k=new StaffService.Key();k.tenantId=tenant();k.staffId=staff;k.serviceId=service;if(add){var x=new StaffService();x.tenantId=k.tenantId;x.staffId=k.staffId;x.serviceId=k.serviceId;assignments.save(x);}else assignments.deleteById(k);}
 public List<StaffAvailability> availability(UUID staff){found(staffs.findByIdAndTenantId(staff,tenant()));return avails.findByTenantIdAndStaffId(tenant(),staff);} @Transactional public StaffAvailability saveAvailability(UUID staff,AvailabilityCommand c,UUID id){admin();if(!c.startTime().isBefore(c.endTime()))throw new IllegalArgumentException("startTime must precede endTime");found(staffs.findByIdAndTenantId(staff,tenant()));var all=availability(staff); if(all.stream().anyMatch(a->!a.id.equals(id)&&a.dayOfWeek==c.dayOfWeek()&&a.type==c.type()&&c.startTime().isBefore(a.endTime)&&c.endTime().isAfter(a.startTime())))throw new IllegalStateException("Overlapping availability window"); StaffAvailability a=id==null?new StaffAvailability():found(avails.findByIdAndTenantId(id,tenant()));a.tenantId=tenant();a.staffId=staff;a.dayOfWeek=c.dayOfWeek();a.startTime=c.startTime();a.endTime=c.endTime();a.type=c.type();return avails.save(a);} @Transactional public void deleteAvailability(UUID id){admin();avails.delete(found(avails.findByIdAndTenantId(id,tenant())));}
 public List<Staff> available(UUID serviceId,Instant start){var s=found(services.findByIdAndTenantId(serviceId,tenant()));return staffs().stream().filter(st->engine.eligible(st,s,assignments.existsByTenantIdAndStaffIdAndServiceId(tenant(),st.id,s.id),availability(st.id),bookings.conflicts(tenant(),st.id,start,start.plusSeconds(s.durationMinutes*60L)),start,zone())).toList();}
 public List<Booking> calendar(Instant from,Instant to){return bookings.findByTenantIdAndStartAtBetween(tenant(),from,to);} @Transactional public Booking book(BookingCommand c){var staff=found(staffs.lockByIdAndTenant(c.staffId(),tenant()));var service=found(services.findByIdAndTenantId(c.serviceId(),tenant()));Instant end=c.startAt().plusSeconds(service.durationMinutes*60L);if(!engine.eligible(staff,service,assignments.existsByTenantIdAndStaffIdAndServiceId(tenant(),staff.id,service.id),availability(staff.id),bookings.conflicts(tenant(),staff.id,c.startAt(),end),c.startAt(),zone()))throw new Conflict("Requested slot is unavailable");var b=new Booking();b.tenantId=tenant();b.staffId=staff.id;b.serviceId=service.id;b.startAt=c.startAt();b.endAt=end;b.status=Model.BookingStatus.CONFIRMED;b.customerName=c.customerName();b.petName=c.petName();return bookings.save(b);} public Booking booking(UUID id){return found(bookings.findByIdAndTenantId(id,tenant()));} @Transactional public Booking cancel(UUID id){var b=booking(id);if(b.status==Model.BookingStatus.CANCELLED)throw new Conflict("Booking already cancelled");b.status=Model.BookingStatus.CANCELLED;return b;}
 public static class Conflict extends RuntimeException{public Conflict(String s){super(s);}}
}
